### ISSUE TITLE
Question about benchmark params

### ISSUE THREAD

**Issue by waghanza** [ohler55/graphql-benchmarks#1]
Hi @ohler55,

I can see `here`
https://github.com/the-benchmarker/graphql-benchmarks/blob/develop/benchmarker.rb#L11
that the number of threads are (by default) the 1/3 x num of proc.

Why this ?

Regards,

**Comment by ohler55** [comment]
That was picked by experimentation. Trying to balance the CPU used by the testing componens and the app itself. That seemed to give the best results for the ones I tested.

-Cheers

**Comment by waghanza** [comment]
How can you figure out those results are the best one ?
This is specific to `perfer`, I mean I use the same settings that **tfb** and they are completely different

**Comment by ohler55** [comment]
They are specific to prefer. Basically I just ran with a different thread count on 3 different machines and picked the counts that showed the best throughput and latency. It worked out to the same or close to 1/3. 

I'm not sure what tbf is but if a different took then I would expect a different ratio might be better. When I tried others they needed more threads and the results were not as good. 

-Pete

**Comment by ohler55** [comment]
Can you tell me what you mean by the results being completely different?

**Comment by waghanza** [comment]
Hi @ohler55,

TFB is a well known benchmark available in https://www.techempower.com/benchmarks/

I have the same **sieger** but not the same results

**Comment by ohler55** [comment]
Looks like I should get Agoo in those benchmarks. 

Showing my ignorance again, what is a sieger?

How were the results different and what did you run? Was the order different across the same apps? Was it GraphQL you were testing?

**Comment by waghanza** [comment]
a `sieger` is the app that stress your stack, for **TFB** or our benchmarks it is https://github.com/wg/wrk or https://github.com/ohler55/perfer but there is a lot of tool 
https://github.com/denji/awesome-http-benchmark

**Comment by ohler55** [comment]
Got it, thanks. Anyway, what kind of differences do you see? Is the relative performance between frameworks the same? Is on of the tools significantly faster than the other? I'm trying to understand the concern.

**Comment by waghanza** [comment]
I just try to understand how results could be so different with `perfer` and `wrk`, and how we could homogenize that :heart:

**Comment by ohler55** [comment]
I'm all for getting consistent results. I understand you say they are different. I need to know how. Are they relatively the same but one consistently higher or lower or does it change the order of the ratings?

**Comment by waghanza** [comment]
This is more a general question, but I am astonished to see that `ruby` outperform `go`

**Comment by ohler55** [comment]
:-) It is the C extension that is doing most of the heavy lifting. If there was more processing going on other than the web server the story would be different.

**Comment by waghanza** [comment]
You are saying that a `pure` `ruby` framework will not outperform `go` ?

**Comment by ohler55** [comment]
That is what I am saying. I would expect a pure Ruby to be less performant than go. One of the nice things about Ruby is that the C extensions can be called with very low overhead so Ruby can be extended readily. Go can be extended but the overhead is calling out to C is much higher.

**Comment by ohler55** [comment]
You got me thinking with the question about go vs ruby. With the current benchmarks what is being tested is mostly the server portion of a GraphQL endpoint. It would be nice to compare how long the GraphQL resolve takes. I would expect go to be faster than Ruby in that case. That would require a more complex example which also opens the door for comparing code complexity or maybe just lines of code needed to implement the GraphQL resolvers. What do you think?

**Comment by waghanza** [comment]
I think your point is very valuable, but requires much efforts ...

It more complex, but very valuable. The value is more for the `core` developers to evaluate bottlenecks than for a business decision.

I have no argue against that, but I can not see how to display results for this analysis

**Comment by ohler55** [comment]
I have some ideas. Let me think about it.

**Comment by ohler55** [comment]
I tried a few approach without much success other than setting up multiple pages for each sort order. That works okay.

As for including a more complex example, maybe that is best as part of the current run averages. I was thinking the average could be over these:

 - simple GET (current)
 - mutation (current)
 - query (expand this and also pull in __type)

The expanded query would be influenced by the http, GraphQL parsing, build in resolvers, calling of user resolvers, and finally some user code. I think that would be a fair mix and would give a better picture of the GraphQL portion that the current benchmarks show.

Anyway, the plan would be in this order.

1. Use multiple pages for different sorted order.
2. Expand the query.
3. Add line count for a complexity score.

What do you think?

**Comment by waghanza** [comment]
Honestly, I do not known much about **GraphQL**. 

The purpose of this repo is to compare performances of each implementations, to be fair implementations **SHOULD** analayse each part of **GraphQL** `standard`, so I think your plan is very OK.

The only point is that I think (but I hope not), the code will be complex.

Could you please make a `PR` in order I have a code in front of that ?

**Comment by ohler55** [comment]
That would be the plan. I was going to create an issue for each of the bullet points, branch for each, and then a PR to merge. Will take my time though. Work gets in the way but starting on a Golang GraphQL to add to the mix.

**Comment by ohler55** [comment]
By the way, I have a new GraphQL in Go ready for public consumption. Just waiting on legal to give a blessing. It is 4 times faster with half the latency. Hope to have that up soon.
