### ISSUE TITLE
gqlgen

### ISSUE THREAD

**Issue by StevenACoffman** [ohler55/graphql-benchmarks#18]
https://gqlgen.com/

+ Language : Go
+ Repo : https://github.com/99designs/gqlgen
+ Author : 99 designs

**Comment by ohler55** [comment]
Can you create a PR and for that?

**Comment by ohler55** [comment]
Are you interested in creating a merge request for gqlgen? If not I'll close this issue.

**Comment by StevenACoffman** [comment]
Sorry, I won't have the time for a while. If I do, I'll just open a pull request.
