### ISSUE TITLE
urql

### ISSUE THREAD

**Issue by homimickey** [ohler55/graphql-benchmarks#19]
+ Language : Typescript  and JavaScript
+ Repo [:FormidableLabs/urql](https://github.com/FormidableLabs/urql)
+ Author :Formidable Labs

**Comment by ohler55** [comment]
Are you interested in creating a merge request for this? If not I'll close the issue.

**Comment by Mahamed-Belkheir** [comment]
From what I can see that's a client, not a server implementation?
