### ISSUE TITLE
Mean vs Average latency?

### ISSUE THREAD

**Issue by deklanw** [ohler55/graphql-benchmarks#8]
Is there a difference between Mean and Average here or is that a mistake?

Thanks

**Comment by ohler55** [comment]
Yes, there is a difference. A google search should give more information. Here is one site http://www.differencebetween.net/science/difference-between-average-and-mean.

Basically the average is the sum of the latencies divided by the number of entries. This tends to be impacted heavily with just a few extreme values. The mean is the middle of the data set and is usually used for bell curve shaped data.

**Comment by deklanw** [comment]
I must admit that this seems unnecessarily divergent from standard usage. For your project,

"average" = "arithmetic mean"
"mean" = "median"

Is that right?

**Comment by ohler55** [comment]
I see what you are getting at now. The terminology is off. I though you were asking about the difference in how they were calculated. I'll change the label from 'mean' to 'median'.

**Comment by deklanw** [comment]
Thank you, that will make it much less confusing, I think!
